title: "Methods of the Sword"
description: "Fencing Articles"
author: "William M. Matthews"
# theme: jekyll-theme-primer # We override this, but this keeps the build stable
url: "https://methodsofthesword.github.io"
baseurl: "/articles" # MUST match your repository name
markdown: kramdown
permalink: /:year/:month/:day/:title/
baseurl: "/articles"
titles_from_headings:
  strip_title: true
  collections: true
github:
  owner: methodsofthesword
  repo: articles
  branch: main