title: "Methods of the Sword Archive"
description: "Fencing Articles and Translations"
author: "Your Name"
theme: jekyll-theme-primer # We override this, but this keeps the build stable
url: "https://methodsofthesword.github.io"
baseurl: "/articles" # MUST match your repository name
markdown: kramdown
permalink: /:year/:month/:day/:title/